var getDate = require('./test')

var past = new Date(1959, 2, 11, 13, 29, 45)
var present = new Date()

function log (str, attr) {
  console.log(str, getDate(attr))
}

function log2 (str, attr) {
  console.log(str, getDate(present, attr))
}

function log3 (str, attr) {
  console.log(str, getDate(past, attr))
}

function frmt (attr) {
  console.log(getDate(attr))
}
console.log()
console.log('------------ FLAGS -----------------')
log('year: ', 'yyyy')
log('year: ', 'yy')
log('month: ', 'm')
log('month: ', 'mm')
log('month: ', 'mmm')
log('month: ', 'mmmm')
log('day: ', 'd')
log('day: ', 'dd')
log('day: ', 'ddd')
log('day: ', 'dddd')
log('ordinal: ', 'o')
log('day: ', 'O')
log('hour: ', 'h')
log('hour: ', 'hh')
log('hour: ', 'H')
log('hour: ', 'HH')
log('minute: ', 'M')
log('minute: ', 'MM')
log('seconds: ', 'S')
log('seconds: ', 'SS')
log('milliseconds: ', 's')
log('milliseconds: ', 'ss')
log('GMT offset: ', 'Z')
log('meridan: ', 't')
log('meridan: ', 'tt')
log('meridan: ', 'T')
log('meridan: ', 'TT')
log('day this year: ', 'N')
log('week this year: ', 'W')
log('quarter this year: ', 'Q')
log('days this month: ', 'u')
log('days this year: ', 'uu')
log('days left this week: ', 'x')
log('days left this month: ', 'xx')
log('days left this year: ', 'xxx')
log('is leap year? ', 'v')
console.log()
console.log('------------ FORMATS -----------------')
frmt('default')
frmt('now')
frmt('shortDate')
frmt('mediumDate')
frmt('longDate'           )
frmt('fullDate'           )
frmt('shortTime'          )
frmt('mediumTime'         )
frmt('longTime'           )
frmt('isoDate'            )
frmt('isoTime'            )
frmt('iso'            )
frmt('isoDateTime'        )
frmt('isoUtcDateTime'     )
frmt('expiresHeaderFormat')
frmt('timestamp'          )

console.log()
console.log('------------ Present Time with Flags -----------------')
log2('year: ', 'yyyy')
log2('year: ', 'yy')
log2('month: ', 'm')
log2('month: ', 'mm')
log2('month: ', 'mmm')
log2('month: ', 'mmmm')
log2('day: ', 'd')
log2('day: ', 'dd')
log2('day: ', 'ddd')
log2('day: ', 'dddd')
log2('ordinal: ', 'o')
log2('day: ', 'O')
log2('hour: ', 'h')
log2('hour: ', 'hh')
log2('hour: ', 'H')
log2('hour: ', 'HH')
log2('minute: ', 'M')
log2('minute: ', 'MM')
log2('seconds: ', 'S')
log2('seconds: ', 'SS')
log2('milliseconds: ', 's')
log2('milliseconds: ', 'ss')
log2('GMT offset: ', 'Z')
log2('meridan: ', 't')
log2('meridan: ', 'tt')
log2('meridan: ', 'T')
log2('meridan: ', 'TT')
log2('day this year: ', 'N')
log2('week this year: ', 'W')
log2('quarter this year: ', 'Q')
log2('days this month: ', 'u')
log2('days this year: ', 'uu')
log2('days left this week: ', 'x')
log2('days left this month: ', 'xx')
log2('days left this year: ', 'xxx')
log2('is leap year? ', 'v')

console.log()
console.log('------------ Past Time with Flags -----------------')
log3('year: ', 'yyyy')
log3('year: ', 'yy')
log3('month: ', 'm')
log3('month: ', 'mm')
log3('month: ', 'mmm')
log3('month: ', 'mmmm')
log3('day: ', 'd')
log3('day: ', 'dd')
log3('day: ', 'ddd')
log3('day: ', 'dddd')
log3('ordinal: ', 'o')
log3('day: ', 'O')
log3('hour: ', 'h')
log3('hour: ', 'hh')
log3('hour: ', 'H')
log3('hour: ', 'HH')
log3('minute: ', 'M')
log3('minute: ', 'MM')
log3('seconds: ', 'S')
log3('seconds: ', 'SS')
log3('milliseconds: ', 's')
log3('milliseconds: ', 'ss')
log3('GMT offset: ', 'Z')
log3('meridan: ', 't')
log3('meridan: ', 'tt')
log3('meridan: ', 'T')
log3('meridan: ', 'TT')
log3('day this year: ', 'N')
log3('week this year: ', 'W')
log3('quarter this year: ', 'Q')
log3('days this month: ', 'u')
log3('days this year: ', 'uu')
log3('days left this week: ', 'x')
log3('days left this month: ', 'xx')
log3('days left this year: ', 'xxx')
log3('is leap year? ', 'v')